project_name: Plywood Gallery
repository_url: https://github.com/kolibril13/plywood-gallery
description: |
  Info: Normal cells are independent of each other, and can be run togehter with the "Header" cell.
  A "Dependent" cell depends on the "Normal" cell left to it.
  A "Dependent" cell depends on another "Dependent" cell left to it.
favicon: favicon.ico
custom_footer: |
  <div style="position: absolute; bottom: 0; right: 0"> <a href="code_animation_idea.html">
  Link to code animating idea!</a></div>
gallary_parameters_path: plywood_gallery/template/gallery_assets/gallery_parameters.json
